// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-ASOw9D/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-ASOw9D/Lp14.tsx")
};
